In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('bp-stats-review-2020-consolidated-dataset-narrow-format.csv')
df

,Country,Year,ISO3166_alpha3,ISO3166_numeric,Region,SubRegion,OPEC,EU,OECD,CIS,Var,Value
0,Algeria,1965,DZA,12.0,Africa,Northern Africa,1.0,0.0,0.0,0.0,wind_twh,0.000000
1,Algeria,1966,DZA,12.0,Africa,Northern Africa,1.0,0.0,0.0,0.0,wind_twh,0.000000
2,Algeria,1967,DZA,12.0,Africa,Northern Africa,1.0,0.0,0.0,0.0,wind_twh,0.000000
3,Algeria,1968,DZA,12.0,Africa,Northern Africa,1.0,0.0,0.0,0.0,wind_twh,0.000000
4,Algeria,1969,DZA,12.0,Africa,Northern Africa,1.0,0.0,0.0,0.0,wind_twh,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...
247797,Zimbabwe,2015,ZWE,716.0,Africa,Eastern Africa,0.0,0.0,0.0,0.0,pop,13.814642
247798,Zimbabwe,2016,ZWE,716.0,Africa,Eastern Africa,0.0,0.0,0.0,0.0,pop,14.030338
247799,Zimbabwe,2017,ZWE,716.0,Africa,Eastern Africa,0.0,0.0,0.0,0.0,pop,14.236599
247800,Zimbabwe,2018,ZWE,716.0,Africa,Eastern Africa,0.0,0.0,0.0,0.0,pop,14.438812
247801,Zimbabwe,2019,ZWE,716.0,Africa,Eastern Africa,0.0,0.0,0.0,0.0,pop,14.645473

In [13]:
df2 = pd.read_csv('bp-stats-review-2020-consolidated-dataset-panel-format.csv')
df2

,Country,Year,pop,ISO3166_alpha3,ISO3166_numeric,Region,SubRegion,OPEC,EU,OECD,...,ren_power_mtoe,ren_power_twh,renewables_ej,renewables_mtoe,solar_ej,solar_mtoe,solar_twh,wind_ej,wind_mtoe,wind_twh
0,Algeria,1965,12.550880,DZA,12.0,Africa,Northern Africa,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Algeria,1966,12.902626,DZA,12.0,Africa,Northern Africa,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Algeria,1967,13.275020,DZA,12.0,Africa,Northern Africa,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Algeria,1968,13.663581,DZA,12.0,Africa,Northern Africa,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Algeria,1969,14.061724,DZA,12.0,Africa,Northern Africa,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6501,Zimbabwe,2015,13.814642,ZWE,716.0,Africa,Eastern Africa,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6502,Zimbabwe,2016,14.030338,ZWE,716.0,Africa,Eastern Africa,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6503,Zimbabwe,2017,14.236599,ZWE,716.0,Africa,Eastern Africa,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6504,Zimbabwe,2018,14.438812,ZWE,716.0,Africa,Eastern Africa,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6505,Zimbabwe,2019,14.645473,ZWE,716.0,Africa,Eastern Africa,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df2.columns

Index(['Country', 'Year', 'pop', 'ISO3166_alpha3', 'ISO3166_numeric', 'Region',
       'SubRegion', 'OPEC', 'EU', 'OECD', 'CIS', 'biodiesel_cons_kbd',
       'biodiesel_cons_kboed', 'biodiesel_cons_ktoe', 'biodiesel_cons_pj',
       'biodiesel_prod_kbd', 'biodiesel_prod_kboed', 'biodiesel_prod_ktoe',
       'biodiesel_prod_pj', 'biofuels_cons_ej', 'biofuels_cons_kbd',
       'biofuels_cons_kboed', 'biofuels_cons_ktoe', 'biofuels_cons_mtoe',
       'biofuels_cons_pj', 'biofuels_prod_kbd', 'biofuels_prod_kboed',
       'biofuels_prod_ktoe', 'biofuels_prod_pj', 'biogeo_ej', 'biogeo_mtoe',
       'biogeo_twh', 'co2_mtco2', 'coalcons_ej', 'coalcons_mtoe',
       'coalprod_ej', 'coalprod_mt', 'coalprod_mtoe', 'cobalt_kt', 'elect_twh',
       'electbyfuel_coal', 'electbyfuel_gas', 'electbyfuel_oil',
       'ethanol_cons_kbd', 'ethanol_cons_kboed', 'ethanol_cons_ktoe',
       'ethanol_cons_pj', 'ethanol_prod_kbd', 'ethanol_prod_kboed',
       'ethanol_prod_ktoe', 'ethanol_prod_pj', 'gascons_bcfd', 'gascons_bcm',
       'gascons_ej', 'gascons_mtoe', 'gasprod_bcfd', 'gasprod_bcm',
       'gasprod_ej', 'gasprod_mtoe', 'gasreserves_tcm', 'graphite_kt',
       'hydro_ej', 'hydro_mtoe', 'hydro_twh', 'liqcons_kbd', 'lithium_kt',
       'nuclear_ej', 'nuclear_mtoe', 'nuclear_twh', 'oilcons_ej',
       'oilcons_kbd', 'oilcons_mt', 'oilcons_mtoe', 'oilprod_crudecond_kbd',
       'oilprod_kbd', 'oilprod_mt', 'oilprod_ngl_kbd', 'oilreserves_bbl',
       'primary_ej', 'primary_gj_pc', 'primary_mtoe', 'rareearths_kt',
       'refcap_kbd', 'refthru_kbd', 'ren_power_ej', 'ren_power_mtoe',
       'ren_power_twh', 'renewables_ej', 'renewables_mtoe', 'solar_ej',
       'solar_mtoe', 'solar_twh', 'wind_ej', 'wind_mtoe', 'wind_twh'],
      dtype='object')

In [15]:
dfoil = df2.drop(['biodiesel_cons_kbd',
       'biodiesel_cons_kboed', 'biodiesel_cons_ktoe', 'biodiesel_cons_pj',
       'biodiesel_prod_kbd', 'biodiesel_prod_kboed', 'biodiesel_prod_ktoe',
       'biodiesel_prod_pj', 'biofuels_cons_ej', 'biofuels_cons_kbd',
       'biofuels_cons_kboed', 'biofuels_cons_ktoe', 'biofuels_cons_mtoe',
       'biofuels_cons_pj', 'biofuels_prod_kbd', 'biofuels_prod_kboed',
       'biofuels_prod_ktoe', 'biofuels_prod_pj', 'biogeo_ej', 'biogeo_mtoe',
       'biogeo_twh', 'co2_mtco2', 'coalcons_ej', 'coalcons_mtoe',
       'coalprod_ej', 'coalprod_mt', 'coalprod_mtoe', 'cobalt_kt', 'elect_twh',
       'electbyfuel_coal', 'electbyfuel_gas', 'electbyfuel_oil',
       'ethanol_cons_kbd', 'ethanol_cons_kboed', 'ethanol_cons_ktoe',
       'ethanol_cons_pj', 'ethanol_prod_kbd', 'ethanol_prod_kboed',
       'ethanol_prod_ktoe', 'ethanol_prod_pj', 'gascons_bcfd', 'gascons_bcm',
       'gascons_ej', 'gascons_mtoe', 'gasprod_bcfd', 'gasprod_bcm',
       'gasprod_ej', 'gasprod_mtoe', 'gasreserves_tcm', 'graphite_kt',
       'hydro_ej', 'hydro_mtoe', 'hydro_twh', 'liqcons_kbd', 'lithium_kt',
       'nuclear_ej', 'nuclear_mtoe', 'nuclear_twh','oilprod_crudecond_kbd',
       'oilprod_kbd', 'oilprod_mt', 'oilprod_ngl_kbd', 'oilreserves_bbl',
       'primary_ej', 'primary_gj_pc', 'primary_mtoe', 'rareearths_kt',
       'refcap_kbd', 'refthru_kbd', 'ren_power_ej', 'ren_power_mtoe',
       'ren_power_twh', 'renewables_ej', 'renewables_mtoe', 'solar_ej',
       'solar_mtoe', 'solar_twh', 'wind_ej', 'wind_mtoe', 'wind_twh'], axis=1)
dfoil.head()

,Country,Year,pop,ISO3166_alpha3,ISO3166_numeric,Region,SubRegion,OPEC,EU,OECD,CIS,oilcons_ej,oilcons_kbd,oilcons_mt,oilcons_mtoe
0,Algeria,1965,12.550880,DZA,12.0,Africa,Northern Africa,1.0,0.0,0.0,0.0,0.055459,26.716192,1.289,1.324613
1,Algeria,1966,12.902626,DZA,12.0,Africa,Northern Africa,1.0,0.0,0.0,0.0,0.072982,35.353233,1.693,1.743139
2,Algeria,1967,13.275020,DZA,12.0,Africa,Northern Africa,1.0,0.0,0.0,0.0,0.068191,33.285973,1.578,1.628722
3,Algeria,1968,13.663581,DZA,12.0,Africa,Northern Africa,1.0,0.0,0.0,0.0,0.072602,35.374426,1.682,1.734076
4,Algeria,1969,14.061724,DZA,12.0,Africa,Northern Africa,1.0,0.0,0.0,0.0,0.076701,37.714329,1.775,1.831980

In [7]:
dfoil['gasreserves_tcm'].unique()

array([       nan, 3.5814625 , 3.540075  , ..., 0.26588869, 0.26533197,
       0.26477525])

In [12]:
dfoil['EU'].unique()

array([0.0, 1.0, None], dtype=object)

In [16]:
dfoil = dfoil.replace({np.nan: 0}).copy()
dfoil.head()

,Country,Year,pop,ISO3166_alpha3,ISO3166_numeric,Region,SubRegion,OPEC,EU,OECD,CIS,oilcons_ej,oilcons_kbd,oilcons_mt,oilcons_mtoe
0,Algeria,1965,12.550880,DZA,12.0,Africa,Northern Africa,1.0,0.0,0.0,0.0,0.055459,26.716192,1.289,1.324613
1,Algeria,1966,12.902626,DZA,12.0,Africa,Northern Africa,1.0,0.0,0.0,0.0,0.072982,35.353233,1.693,1.743139
2,Algeria,1967,13.275020,DZA,12.0,Africa,Northern Africa,1.0,0.0,0.0,0.0,0.068191,33.285973,1.578,1.628722
3,Algeria,1968,13.663581,DZA,12.0,Africa,Northern Africa,1.0,0.0,0.0,0.0,0.072602,35.374426,1.682,1.734076
4,Algeria,1969,14.061724,DZA,12.0,Africa,Northern Africa,1.0,0.0,0.0,0.0,0.076701,37.714329,1.775,1.831980

In [17]:
dfoil.to_csv('oil_con_by_year_country.csv')